### ISSUE TITLE
Sound comes with a lot of static

### ISSUE THREAD

**Issue by Borgesvpm** [Ibrahim2750mi/PyMusic-Instrument#1]
I can hear the sound when I run the script, but it comes with an unbearable amount of static.

https://user-images.githubusercontent.com/44777359/154684919-d3b130f0-5558-4e45-8cab-6230e848d807.mp4

**Comment by Ibrahim2750mi** [comment]
Recommended bitrate is 44100 or 48000, the static comes at the end right?

**Comment by Ibrahim2750mi** [comment]
this issue will be close if no further reply is received under one week.
